blank_issues_enabled: false
contact_links:
    - name: Leave a Review
      url: https://marketplace.visualstudio.com/items?itemName=bolt-builder.bolt-code&ssr=false#review-details
      about: Enjoying Bolt Code? Leave a review here!
